# application-dev.yml
server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.72:8848
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0